#!/bin/bash

#./dependecies

#This script install all the tools required for CGRA execution on the framework.

#=============================================================
#Modify Instruction Generator Source
directory=$(pwd)
newpath="$directory"
oldpath="/home/cml/CGRA"
sed -i "s|$oldpath|$newpath|g" $newpath/InstructionGenerator/insgen.cpp

#build Instruction Generator
cd 2.0/InstructionGenerator
g++ -static insgen.cpp -o insgen 
cd ../

#=============================================================

#Enter REGIMap to build it. 
cd REGIMap/REGIMap_2.8/Release/
make
cd ../../../

#===========================================================

#Enter gem5 to build. 
cd gem5
scons build/ARM/gem5.opt
cp ../Dependencies/ARM build/variables/ 
scons build/ARM/gem5.opt
cd ../

#===========================================================

#Enter llvm directory to build llvm
cd llvm
rm -rf build
mkdir build
cd build
cp ../Makefile.rules .
../configure
cp Makefile.config Makefile.config.in
make -j4
cd ../../

#Making DFG generation LLVM Pass. 
cp -r MahdiLoop llvm/build/lib/Transfoms/ 
cd llvm/build/lib/Transforms/MahdiLoop/
make

#==========================================================
